service: brandy-api

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-north-1'}
  stage: ${opt:stage, 'development'}
  logRetentionInDays: 90
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}

functions:
  API:
    handler: main.handle
    module: api
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60

custom:
  pythonRequirements:
    noDeploy:
      - boto3 # already on Lambda
      - botocore # already on Lambda

plugins:
  - serverless-python-requirements
